import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  Button,
  OverriddenButton,
  StyledButton,
  ThemedButton,
  FinalButton,
} from "../components";
import { Button as MuiButton } from "@mui/material";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nestsolutions.llc">Nest solutions LLC</a>
        </h1>
        <i>Please read about this project. [link]</i>

        <p className={styles.description}>
          Let's see how it works.
          <code className={styles.code}>components/Button.tsx</code>
        </p>
        <div className={styles.grid}>
          <div className={styles.card}>
            <h3>Without any style </h3>
            <Button text="Button" />
          </div>
          <div className={styles.card}>
            <h3>With css </h3>
            <StyledButton text="Button" />
          </div>
          <div className={styles.card}>
            <h3>Wrapped theme provider </h3>
            <ThemedButton text="Button" />
          </div>
          <div className={styles.card}>
            <h3>Styled Mui button using sx </h3>
            <MuiButton
              variant="contained"
              color="secondary"
              sx={{
                padding: 5,
              }}
            >
              Button
            </MuiButton>
          </div>
          <div className={styles.card}>
            <h3>Override styles with class name </h3>
            <MuiButton
              variant="contained"
              color="secondary"
              disabled
              sx={{
                padding: 5,
                "&.Mui-disabled": {
                  border: "2px solid black",
                  borderRadius: "20%",
                },
              }}
            >
              Button
            </MuiButton>
          </div>
          <div className={styles.card}>
            <h3> Styled component</h3>
            <OverriddenButton text="button"></OverriddenButton>
          </div>
          <p className={styles.description}>
            Final button's look
            <code className={styles.code}>components/Button.tsx</code>
          </p>
          <div className={styles.grid}>
            {["fill", "transparent", "text", "underline"].map(
              (variant, key) => {
                return (
                  <div style={{ marginLeft: "50px" }}>
                    <h3>{variant}</h3>
                    <FinalButton text="Button" variant={variant} key={key} />
                    <div style={{ height: "50px", width: "50px" }} />
                    <FinalButton
                      text="Disabled"
                      variant={variant}
                      disabled
                      key={key}
                    />
                  </div>
                );
              }
            )}
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
