import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Button, FinalButton, StyledButton, ThemedButton } from "../components";
import { Button as MuiButton } from "@mui/material";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nestsolutions.llc">Nest solutions LLC</a>
        </h1>

        <p className={styles.description}>
          Let's see how it works.
          <code className={styles.code}>components/Button.tsx</code>
        </p>
        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Without any style </h2>
            <Button text="Button" />
          </div>
          <div className={styles.card}>
            <h2>With css </h2>
            <StyledButton text="Button" />
          </div>
          <div className={styles.card}>
            <h2>Wrapped theme provider </h2>
            <ThemedButton text="Button" />
          </div>
          <div className={styles.card}>
            <h2>Styled Mui button using sx </h2>
            <MuiButton
              variant="contained"
              color="secondary"
              sx={{
                padding: 5,
              }}
            >
              Button
            </MuiButton>
          </div>
          <div className={styles.card}>
            <h2>Override styles with class name </h2>
            <MuiButton
              variant="contained"
              color="secondary"
              disabled
              sx={{
                padding: 5,
                "&.Mui-disabled": {
                  border: "2px solid black",
                  borderRadius: "20%",
                },
              }}
            >
              Button
            </MuiButton>
          </div>
          <div className={styles.card}>
            <h2> Styled component</h2>
            <FinalButton text="button"></FinalButton>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
